function [fitresult, gof] = createInterpolant2DFit(r, c, z, optional_title, optional_number)
%CREATEFIT(R,C,Z)
%  Create a fit.
%
%  Data for 'Interpolant 2D fit' fit:
%      X Input : r
%      Y Input : c
%      Z Output: z
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Oct-2018 15:31:15


%% Fit: 'Interpolant 2D fit'.
[xData, yData, zData] = prepareSurfaceData( r, c, z );

% Set up fittype and options.
ft = 'thinplateinterp';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, 'Normalize', 'on' );

% Plot fit with data.

if exist('optional_title','var')

    if ~exist('optional_number','var')
        figure( 'Name', optional_title );        
    else
        figure( optional_number);
        set(gcf,'Name', optional_title );
    end
    
    h = plot( fitresult, [xData, yData], zData );
    legend( h, 'Interpolant 2D fit', 'z vs. r, c', 'Location', 'NorthEast' );
    % Label axes
    xlabel r
    ylabel c
    zlabel z
    grid on
    view( -12.3, 19.6 );
        title(['Plane fit r^2 = ' num2str(gof.rsquare) ' | ' optional_title],'FontSize',16)

    
end


